import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const downloadFileQuery = api.example.downloadFile.useMutation();
  const [url, setUrl] = useState("");
  const handleClick = () => {
    downloadFileQuery.mutate(undefined, {
      onSuccess: (data) => {
        setUrl(data.url);
      },
    });
  };

  let statusMessage = "";
  if (downloadFileQuery.isLoading) {
    statusMessage = "Generating URL...";
  }
  if (downloadFileQuery.isError) {
    statusMessage = "Error generating URL";
  }

  useEffect(() => {
    if (downloadFileQuery.isSuccess && url !== "") {
      window.open(url, "_blank");
    }
  }, [downloadFileQuery.isSuccess, url]);

  return (
    <>
      <Head>
        <title>Demo Azure Storage Download</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-center text-6xl font-bold text-white">
            Can YOU find the secret password ?
          </h1>
          <Image
            alt="Dora"
            width={300}
            height={300}
            src="https://static.wikia.nocookie.net/doratheexplorer/images/c/cf/Vlcsnap-2022-01-06-22h41m43s720.png/revision/latest/scale-to-width-down/300?cb=20220107034227"
          />
          <button
            className="rounded-md bg-white px-4 py-2 text-black"
            onClick={handleClick}
          >
            Generate File
          </button>
          <h2 className="text-center text-xl text-white">{statusMessage}</h2>
          {downloadFileQuery.isSuccess ? (
            <a
              href={url}
              download={true}
              target="_blank"
              className="px-4 py-2 text-white underline"
            >
              Download your file here
            </a>
          ) : null}
        </div>
      </main>
    </>
  );
};

export default Home;
